# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Todo add some better report details here
      - run: yarn lint

      - run: yarn test

      - run: yarn build

  deploy-staging:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to staging S3
          command: aws s3 sync build s3://jupiter-assets.s3-us-west-2.amazonaws.com/staging/ --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - approve-deploy-to-staging:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-staging:
          requires:
            - approve-deploy-to-staging