# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      - image: circleci/node:12.13.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn test

      - run: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-staging:
    docker:
      - image: circleci/python:2.7

    steps:
      - attach_workspace:
          at: .

      - aws-s3/sync:
          from: build
          to: 's3://staging-jupiter-assets/jupiter'
          arguments: '--acl public-read'
          overwrite: true

  deploy-prod:
    docker:
      - image: circleci/python:2.7

    steps:
      - attach_workspace:
          at: .

      - aws-s3/sync:
          from: build
          to: 's3://prod-jupiter-assets/jupiter'
          arguments: '--acl public-read'
          overwrite: true

mster_only: &master_only
  filters:
    branches:
      only:
        - master

not_master: &not_master
  filters:
    branches:
      ignore:
        - master

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - staging-deploy-ask:
          <<: *not_master
          type: approval
          requires:
            - build
      - deploy-staging:
          <<: *not_master
          requires:
            - staging-deploy-ask
      - deploy-prod:
            <<: *master_only
            requires:
              - build
