# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn test

      - run: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-staging:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - run: "mkdir assets"
      - run: "ls -la"
      - attach_workspace:
          at: ./assets

      - run: "ls -la ./assets"

      - aws-s3/sync:
          from: assets
          to: 's3://jupiter-assets/staging'
          arguments: '--acl public-read'
          overwrite: true

  deploy-prod:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - aws-s3/sync:
          from: build
          to: 's3://jupiter-assets/prod'
          arguments: '--acl public-read'
          overwrite: true

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - staging-deploy-ask:
          type: approval
          requires:
            - build
      - deploy-staging:
          requires:
            - staging-deploy-ask
      - prod-deploy-ask:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - deploy-staging
            - prod-deploy-ask
          filters:
            branches:
              only: master